// <auto-generated />
using System;
using AGSDocumentInfrastructureEF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AGSDocumentGraphQL.Migrations.Application.EFDbContextMigration
{
    [DbContext(typeof(EFDbContext))]
    partial class EFDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.17");

            modelBuilder.Entity("AGSDocumentInfrastructureEF.Entities.EFAGSFile", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("FileExtension")
                        .HasColumnType("longtext");

                    b.Property<string>("FilePath")
                        .HasColumnType("longtext");

                    b.Property<string>("FolderId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<int>("SizeInByte")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FolderId");

                    b.ToTable("Files");
                });

            modelBuilder.Entity("AGSDocumentInfrastructureEF.Entities.EFAGSFolder", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<string>("ParentFolderId")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Folders");
                });

            modelBuilder.Entity("AGSDocumentInfrastructureEF.Entities.EFAGSFolderPermission", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("DepartmentId")
                        .HasColumnType("longtext");

                    b.Property<string>("FolderId")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("PermissionType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FolderId");

                    b.ToTable("FolderPermissions");
                });

            modelBuilder.Entity("AGSDocumentInfrastructureEF.Entities.EFAGSFile", b =>
                {
                    b.HasOne("AGSDocumentInfrastructureEF.Entities.EFAGSFolder", "EFAGSFolder")
                        .WithMany("EFAGSFiles")
                        .HasForeignKey("FolderId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("EFAGSFolder");
                });

            modelBuilder.Entity("AGSDocumentInfrastructureEF.Entities.EFAGSFolderPermission", b =>
                {
                    b.HasOne("AGSDocumentInfrastructureEF.Entities.EFAGSFolder", "Folder")
                        .WithMany("EFAGSFolderPermissions")
                        .HasForeignKey("FolderId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Folder");
                });

            modelBuilder.Entity("AGSDocumentInfrastructureEF.Entities.EFAGSFolder", b =>
                {
                    b.Navigation("EFAGSFiles");

                    b.Navigation("EFAGSFolderPermissions");
                });
#pragma warning restore 612, 618
        }
    }
}
